### ISSUE TITLE
gen run basics/service error

### ISSUE THREAD

**Issue by lujg** [wzshiming/gen#1]
I have follwed the examples'steps and installed the gen app. But when I run command `gen run github.com/wzshiming/gen/examples/basics/service`, I get error like this:
>  json: error calling MarshalJSON for type *spec.Response: json: error calling MarshalJSON for type *spec.Schema: json: error calling MarshalJSON for type spec.Any: unexpected end of JSON input

Can anyone tell me how can I fix this problem?

**Comment by wzshiming** [comment]
The version dependent on the library is updated, now the vendor has been added.

Update it.
`
go get -u github.com/wzshiming/gen/cmd/gen
`
`
go install github.com/wzshiming/gen/cmd/gen 
`

Try again
`
gen run github.com/wzshiming/gen/examples/basics/service
`

Thanks you.

**Comment by lujg** [comment]
Thank you, the example works.

**Comment by wzshiming** [comment]
Some features aren't implemented yet. It is not ready for production use.
